import '../models/recent_article_model.dart';

final articles = [
  Article(
    articleId: 1,
    author: 'Shrek',
    title: "Shrek dreamwork ",
    imgUrl: "https://tinyurl.com/88fmpjmc",
    likeCount: 123,
    readCount: 234,
    authorFirstName: "hagos",
    authorLastName: "",
    body: "",
    category: "",
    readingDuration: "45:30",
    createDate: "02/02/2023",
  ),
  Article(
    articleId: 2,
    author: 'Yemane',
    title: "The life of the man",
    imgUrl: "https://tinyurl.com/88fmpjmc",
    likeCount: 423,
    readCount: 334,
    authorFirstName: "Ghirmay",
    authorLastName: "",
    body: "",
    category: "",
    readingDuration: "30:15",
    createDate: "02/02/2023",
  ),
  Article(
    articleId: 1,
    author: 'Not known',
    title: "Joy of the Earth",
    imgUrl: "https://tinyurl.com/yyy4ypj4",
    likeCount: 400,
    readCount: 340,
    authorFirstName: "Alazar",
    authorLastName: "",
    body: "",
    category: "",
    readingDuration: "20:30",
    createDate: "02/02/2023",
  ),
  Article(
    articleId: 1,
    author: 'Debesay',
    title: "Zngbaba",
    imgUrl: "https://tinyurl.com/yvk8yj8f",
    likeCount: 500,
    readCount: 458,
    authorFirstName: "Neguse",
    authorLastName: "TULUK",
    body: "",
    category: "",
    readingDuration: "5:30",
    createDate: "02/02/2023",
  ),
  Article(
    articleId: 1,
    author: 'Jenifer',
    title: "The lord of the earth",
    imgUrl: "https://tinyurl.com/4cvzhm4m",
    likeCount: 123,
    readCount: 234,
    authorFirstName: "Neguse",
    authorLastName: "Tuluk",
    body: "",
    category: "",
    readingDuration: "12:30",
    createDate: "12/02/2023",
  ),
  Article(
    articleId: 1,
    author: 'Mesi',
    title: "The players of football",
    imgUrl: "https://tinyurl.com/29b9c62m",
    likeCount: 578,
    readCount: 564,
    authorFirstName: "Naoda",
    authorLastName: "",
    body: "",
    category: "",
    readingDuration: "10:30",
    createDate: "02/02/2023",
  ),
];
