import '../models/recent_article_model.dart';

bool isBookMarked = true;
final articles = [
  Article(
    articleId: 1,
    author: 'Shrek',
    title: "Shrek dreamwork ",
    imgUrl: "https://tinyurl.com/88fmpjmc",
    description:
        "Nelson Rolihlahla Mandela was a South African anti-apartheid activist and politician who served as the first  president of South Africa from 1994 to 1999. He was the country's first black head of state and the first elected in a fully representative democratic election.",
    likeCount: 123,
    readCount: 234,
    authorFirstName: "hagos",
    authorLastName: "",
    body: "",
    category: "",
    isBookMarked: false,
    readingDuration: "45:30",
    createDate: "02/02/2023",
  ),
  Article(
    articleId: 2,
    author: 'Yemane',
    title: "The life of the man",
    imgUrl: "https://tinyurl.com/88fmpjmc",
    description:
        "Nelson Rolihlahla Mandela was a South African anti-apartheid activist and politician who served as the first  president of South Africa from 1994 to 1999. He was the country's first black head of state and the first elected in a fully representative democratic election.",
    likeCount: 423,
    readCount: 334,
    authorFirstName: "Ghirmay",
    authorLastName: "",
    body: "",
    category: "",
    isBookMarked: false,
    readingDuration: "30:15",
    createDate: "02/02/2023",
  ),
  Article(
    articleId: 3,
    author: 'Not known',
    title: "Joy of the Earth",
    imgUrl: "https://tinyurl.com/yyy4ypj4",
    description:
        "Nelson Rolihlahla Mandela was a South African anti-apartheid activist and politician who served as the first  president of South Africa from 1994 to 1999. He was the country's first black head of state and the first elected in a fully representative democratic election.",
    likeCount: 400,
    readCount: 340,
    authorFirstName: "Alazar",
    authorLastName: "",
    body: "",
    category: "",
    isBookMarked: true,
    readingDuration: "20:30",
    createDate: "02/02/2023",
  ),
  Article(
    articleId: 4,
    author: 'Debesay',
    title: "Zngbaba",
    imgUrl: "https://tinyurl.com/yvk8yj8f",
    description:
        "Nelson Rolihlahla Mandela was a South African anti-apartheid activist and politician who served as the first  president of South Africa from 1994 to 1999. He was the country's first black head of state and the first elected in a fully representative democratic election.",
    likeCount: 500,
    readCount: 458,
    authorFirstName: "Neguse",
    authorLastName: "TULUK",
    body: "",
    category: "",
    isBookMarked: true,
    readingDuration: "5:30",
    createDate: "02/02/2023",
  ),
  Article(
    articleId: 5,
    author: 'Jenifer',
    title: "The lord of the earth",
    imgUrl: "https://tinyurl.com/4cvzhm4m",
    description:
        "Nelson Rolihlahla Mandela was a South African anti-apartheid activist and politician who served as the first  president of South Africa from 1994 to 1999. He was the country's first black head of state and the first elected in a fully representative democratic election.",
    likeCount: 123,
    readCount: 234,
    authorFirstName: "Neguse",
    authorLastName: "Tuluk",
    body: "",
    category: "",
    isBookMarked: true,
    readingDuration: "12:30",
    createDate: "12/02/2023",
  ),
  Article(
    articleId: 5,
    author: 'Mesi',
    title: "The players of football",
    imgUrl: "https://tinyurl.com/29b9c62m",
    description:
        "Nelson Rolihlahla Mandela was a South African anti-apartheid activist and politician who served as the first  president of South Africa from 1994 to 1999. He was the country's first black head of state and the first elected in a fully representative democratic election.",
    likeCount: 578,
    readCount: 564,
    authorFirstName: "Naoda",
    authorLastName: "",
    body: "",
    category: "",
    isBookMarked: false,
    readingDuration: "10:30",
    createDate: "02/02/2023",
  ),
];
